//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Books
    {
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public string Book_Writer { get; set; }
        public Nullable<int> Book_NumOfPages { get; set; }
        public string Book_Publisher { get; set; }
        public string Book_Lang { get; set; }
        public string Book_Description { get; set; }
        public string Book_YearOfPrinting { get; set; }
    }
}
