//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookReserve
    {
        public int Reserve_ID { get; set; }
        public Nullable<int> Book_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Book_Name { get; set; }
        public Nullable<System.DateTime> Reserver_Date { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
    }
}
